### ISSUE TITLE
Lua error during combat

### ISSUE THREAD

**Issue by Gilverion** [Dinocool/soulaire-party-frames#1]
I am getting the following lua error, when infight and "Show Player Frame in Party Frame" is toggled. It seems to occur, when i am not in a party.

1x [ADDON_ACTION_BLOCKED] AddOn 'SoulairePartyFrames' tried to call the protected function 'SUFHeaderpartyUnitButton1:Hide()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `Hide'
[string "@Blizzard_FrameXML/SecureGroupHeaders.lua"]:232: in function <...faceBlizzard_FrameXML/SecureGroupHeaders.lua:130>
[string "@Blizzard_FrameXML/SecureGroupHeaders.lua"]:406: in function `SecureGroupHeader_Update'
[string "@Blizzard_FrameXML/SecureGroupHeaders.lua"]:62: in function <...faceBlizzard_FrameXML/SecureGroupHeaders.lua:60>
[string "=[C]"]: ?

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

**Comment by Dinocool** [comment]
this should be fixed now.
