### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Spydawg** [Dinocool/soulaire-party-frames#2]
`3x ...eSoulairePartyFrames/Core/SoulPartyFrame.lua:55: attempt to index global 'DevTool' (a nil value)
[string "@SoulairePartyFrames/Core/SoulPartyFrame.lua"]:55: in function `CreateHeader'
[string "@SoulairePartyFrames/Core/SoulPartyFrame.lua"]:97: in function <...eSoulairePartyFrames/Core/SoulPartyFrame.lua:96>
[string "=[C]"]: in function `Show'
[string "@SoulairePartyFrames/Config/Init.lua"]:36: in function <SoulairePartyFrames/Config/Init.lua:24>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = Frame {
 headerFrame = SUFHeaderparty {
 }
}
type = "party"
headerFrame = SUFHeaderparty {
}
secureInitializeUnit = "	local header = self:GetParent()

	self:SetAttribute("*type1", "target")
	self:SetAttribute("*type2", "togglemenu")
	self:SetAttribute("type2", "togglemenu")

	self:SetWidth("232")
	self:SetHeight("100")

	header:CallMethod("initialConfigFunction", self:GetName())
"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "initialconfigfunction"
(*temporary) = "attempt to index global 'DevTool' (a nil value)"
`

**Comment by Dinocool** [comment]
fixed, my bad here.

**Comment by Spydawg** [comment]
Can confirm, works great. thanks
