### ISSUE TITLE
Error in M+

### ISSUE THREAD

**Issue by Spydawg** [Dinocool/soulaire-party-frames#3]
`1x [ADDON_ACTION_BLOCKED] AddOn 'SoulairePartyFrames' tried to call the protected function 'CompactPartyFrameMember2:SetSize()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetSize'
[string "@Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua"]:1973: in function `updateAllSetupFunc'
[string "@Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua"]:405: in function `CompactUnitFrame_UpdateAll'
[string "@Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua"]:62: in function <...Ons/Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua:53>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}
`

**Comment by Dinocool** [comment]
should now be fixed.
