### ISSUE TITLE
LUA Error when leveling up while in combat (?)

### ISSUE THREAD

**Issue by deadlydag** [Dinocool/soulaire-party-frames#4]
2x [ADDON_ACTION_BLOCKED] AddOn 'SoulairePartyFrames' tried to call the protected function 'Frame:SetScale()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetScale'
[string "@SoulairePartyFrames/Core/SoulPartyFrame.lua"]:82: in function `SoulPartyFrame_UpdateSettingFrameSize'
[string "@SoulairePartyFrames/Config/Init.lua"]:54: in function `ChangeRole'
[string "@SoulairePartyFrames/Core/SoulPartyFrame.lua"]:156: in function <...eSoulairePartyFrames/Core/SoulPartyFrame.lua:153>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

**Comment by Dinocool** [comment]
should be fixed now.
